image:
- Visual Studio 2017

# Install scripts.
install:
- nuget restore
- msbuild minerstat.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  
artifacts:
- path: minerstat/bin/x86/Debug
  name: minerstat-windows

deploy:
- provider: GitHub
  tag: latest
  release: continuous build - up to date with commits
  auth_token:
    secure: vdH/WFjpv+yuUkzohJhhxPD5EtAhnBoGc0p/7+mghQSM2Grza+NZlxgN3sFux1DT
  repository: minerstat/minerstat-windows
  prerelease: true
  force_update: true

# Don't actually build.
build: off
